### ISSUE TITLE
[Bug]: Update fails, update window doesn't scroll

### ISSUE THREAD

**Issue by murolem** [Project-Elixir/issue_tracker#10]
### Issue type

User interface

### Exact version and Build date

v3.13

### Bug Description

1. Update page doesn't scroll. barely can press buttons below.
2. Update download stops after a while. Was having this issue since some previous update, had to install it manually.

It's also lagging like ass when the update is downloading.

Model: Redmi note 10 pro
I have 60 gigs of free space.

### Steps to Reproduce

1. Go into update page
2. Press update

### Screenshots or Videos

![Screenshot_20240116-163630_Настройки](https://github.com/Project-Elixir/issue_tracker/assets/20380250/f0a1d8e9-13d0-43a1-8734-ad7b4ab96259)
![Screenshot_20240116-163605_Обновление Elixir](https://github.com/Project-Elixir/issue_tracker/assets/20380250/b5a0b6d0-41b7-4e71-80ad-b2387ebc8427)

### Acknowledgements

- [X] I have checked that the device is officially supported (for device specific reports and not source related).
- [X] I am running the latest version available on projectelixiros.com for this device.
- [X] I have searched the existing issues and this is a new issue and not a duplicate of any another open issue.
- [X] I have written a short but informative title.
- [X] I have filled out all of the requested information in this issue properly.

**Comment by murolem** [comment]
@nishant6342 hi!
why is this closed?

**Comment by nishant6342** [comment]
> @nishant6342 hi! why is this closed?

fixed in 4.X versions it doesnt freezes now

**Comment by murolem** [comment]
> > @nishant6342 hi! why is this closed?
> 
> fixed in 4.X versions it doesnt freezes now

How do I update to it then?

**Comment by nishant6342** [comment]
> > > @nishant6342 hi! why is this closed?
> > 
> > 
> > fixed in 4.X versions it doesnt freezes now
> 
> How do I update to it then?

download new rom zip and flash using recovery mode then u can use updater in future
