### ISSUE TITLE
[Bug]: Spotify connect to device causes crash

### ISSUE THREAD

**Issue by blduncan** [Project-Elixir/issue_tracker#17]
### Issue type

Feature not working as intended

### Exact version and Build date

V4 | 2024-01-31

### Bug Description

Connecting to external device in the Spotify app causes the screen to flicker on and off. Touch controls and lock buttons don't function.

### Steps to Reproduce

1. Open Spotify.
2. Tap devices and select a device to connect to(e.g. Google Home speaker)

### Solution

Had to factory reset.

### Acknowledgements

- [X] I have checked that the device is officially supported (for device specific reports and not source related).
- [X] I am running the latest version available on projectelixiros.com for this device.
- [X] I have searched the existing issues and this is a new issue and not a duplicate of any another open issue.
- [X] I have written a short but informative title.
- [X] I have filled out all of the requested information in this issue properly.

**Comment by nishant6342** [comment]
We are working on it to fix this bug! Expect this to be fixed in next update

**Comment by nishant6342** [comment]
Its fixed! wait for update to arrive to your phone
