### ISSUE TITLE
Redmi K20 Pro: UDFPS bloom animation not working 

### ISSUE THREAD

**Issue by HareeshRom** [Project-Elixir/issue_tracker#20]
### Issue type

User interface

### Exact version and Build date

v4.1 | 24-2-2024

### Bug Description

UDFPS bloom effect is not working, remaining all UDFPS is working.

![20240224_200720](https://github.com/Project-Elixir/issue_tracker/assets/161140841/03bad9a9-d6fb-4425-8a46-931dbbc7c053)

### Steps to Reproduce

Step 1. Settings
Step 2. Essence
Step 3. Lock screen
Step 4. UDFPS custom animation
Step 5. Bloom effect (animation) not working 

### Acknowledgements

- [X] I have checked that the device is officially supported (for device specific reports and not source related).
- [X] I am running the latest version available on projectelixiros.com for this device.
- [X] I have searched the existing issues and this is a new issue and not a duplicate of any another open issue.
- [X] I have written a short but informative title.
- [X] I have filled out all of the requested information in this issue properly.

**Comment by nishant6342** [comment]
Thanks for reporting! Will be fixed in next update

**Comment by HareeshRom** [comment]
One more bug also their bro, ui suddenly stop working (back gesture and
home swipe gesture) not work, and then we have to drag notification panel
and click settings, then again back gesture and home swipe gesture works
properly, and it repeats constantly, ( it only happens in 4.1 update)
thanks for your concern.
