### ISSUE TITLE
[Bug]: reconocer rostro dentro de al App bancaria no funciona 

### ISSUE THREAD

**Issue by AlxKing3652hjw** [Project-Elixir/issue_tracker#21]
### Issue type

Other

### Exact version and Build date

V4.1 25/02/2024

### Bug Description

Se pone en blanco al querer registrar mi rostro
![Screenshot_20240225-205517](https://github.com/Project-Elixir/issue_tracker/assets/161268529/1b6e7237-cf3f-46b9-8cf6-96805e9cc3d7)

### Steps to Reproduce

Verificar en los dispositivos mi 10 y las app de banco

### Screenshots or Videos

![Screenshot_20240225-205517](https://github.com/Project-Elixir/issue_tracker/assets/161268529/cb2133cf-d2a5-45b3-b551-f716dd5472e0)

### Acknowledgements

- [X] I have checked that the device is officially supported (for device specific reports and not source related).
- [X] I am running the latest version available on projectelixiros.com for this device.
- [X] I have searched the existing issues and this is a new issue and not a duplicate of any another open issue.
- [X] I have written a short but informative title.
- [X] I have filled out all of the requested information in this issue properly.

**Comment by nishant6342** [comment]
Sorry we can,t understand your language, open another issue in english language please
