### ISSUE TITLE
NFC Tile[Bug]: 

### ISSUE THREAD

**Issue by Gollumix** [Project-Elixir/issue_tracker#23]
### Issue type

Feature not working as intended

### Exact version and Build date

4.1 2024.02.26

### Bug Description

NFC Tile is showing as Unavailable, but NFC still working when turned on in settings.

Device: OnePlus 5T (dumpling) 

### Steps to Reproduce

It's like this after installing rom. 

### Screenshots or Videos

![Screenshot_20240228-100422](https://github.com/Project-Elixir/issue_tracker/assets/107421553/2a3f6130-64b6-4d03-a0a8-87267fd085ba)

### Acknowledgements

- [X] I have checked that the device is officially supported (for device specific reports and not source related).
- [X] I am running the latest version available on projectelixiros.com for this device.
- [X] I have searched the existing issues and this is a new issue and not a duplicate of any another open issue.
- [X] I have written a short but informative title.
- [X] I have filled out all of the requested information in this issue properly.

**Comment by nishant6342** [comment]
Fixed, wait for next update for your device ;-)
