### ISSUE TITLE
[Bug]: Lockscreen PIN-buttons not scaling properly

### ISSUE THREAD

**Issue by TekkertheChaot** [Project-Elixir/issue_tracker#29]
### Issue type

User interface

### Exact version and Build date

V4.1 | UQ1A.240205.004

### Bug Description

The lockscreen numerical buttons for unlocking the device (not the SIM-PIN) have become tiny and hard to accurately press.
They do scale with the System DPI but it behaving very awkwardly. Also hitting them in this smaller state is really bothersome,

### Steps to Reproduce

Step 1: set up your display DPI / content size to a very high / very low value.
Step 2: Lock the Screen
Step 3: swipe up to show the buttons

### Screenshots or Videos

![Screenshot_20240218-000905](https://github.com/Project-Elixir/issue_tracker/assets/17234581/f1d6b14b-2324-443f-bc2e-ec70bd405024)
![Screenshot_20240218-000833](https://github.com/Project-Elixir/issue_tracker/assets/17234581/7ed154d1-79c3-4e3f-800d-03d2d29d0de7)
![Screenshot_20240218-000844](https://github.com/Project-Elixir/issue_tracker/assets/17234581/3d0aa874-8b1f-4715-b04a-4c3da80e7bc3)

### Additional Context

Device: fajita (OnePlus 6T)
Rooted: false
Magisk modules: none
Build: UQ1A.240205.004
Kernel: built-in kernel
Third-Party Mods: none

### Acknowledgements

- [X] I have checked that the device is officially supported (for device specific reports and not source related).
- [X] I am running the latest version available on projectelixiros.com for this device.
- [X] I have searched the existing issues and this is a new issue and not a duplicate of any another open issue.
- [X] I have written a short but informative title.
- [X] I have filled out all of the requested information in this issue properly.

**Comment by manidweep** [comment]
lockscreen is source issue and known

**Comment by TekkertheChaot** [comment]
Alright, thanks for the info!

**Comment by ugly-kid-af** [comment]
Fixed !!
