### ISSUE TITLE
[Bug]: In landscape mode notifications doesn't pop up

### ISSUE THREAD

**Issue by pure-soul-kk** [Project-Elixir/issue_tracker#3]
### Issue type

User interface

### Exact version and Build date

v3.12

### Bug Description

While watching videos or doing any task in landscape the notification icon with the status bar only appears the notification doesn't pop up

### Steps to Reproduce

Switch to landscape mode and observe

### Acknowledgements

- [x] I have checked that the device is officially supported (for device specific reports and not source related).
- [X] I am running the latest version available on projectelixiros.com for this device.
- [X] I have searched the existing issues and this is a new issue and not a duplicate of any another open issue.
- [X] I have written a short but informative title.
- [X] I have filled out all of the requested information in this issue properly.

**Comment by nishant6342** [comment]
will looks into it asap
