### ISSUE TITLE
[Suggestion]: Add option to hide user select on single user system

### ISSUE THREAD

**Issue by TekkertheChaot** [Project-Elixir/issue_tracker#30]
### Issue type

User interface

### Exact version and Build date

V4.1 | UQ1A.240205.004

### Bug Description

The User selector is always visible, even on a single user system with disabled multi-user management.
Also a quirk: most of the time, the user name is not even shown and it is jsut a lonely empty dropdown menu...

### Steps to Reproduce

Step 1: disable Multi-user management in Settings -> Your top profile card -> Allow multiple users
Step 2: lock the screen
Step 3: swipe up to see the PIN entry

### Screenshots or Videos

![Screenshot_20240306-181756](https://github.com/Project-Elixir/issue_tracker/assets/17234581/f7c4a2ba-eeac-494d-9c6a-5a1282508e33)

### Additional Context

Device: fajita (OnePlus 6T)
Rooted: false
Magisk modules: none
Build: UQ1A.240205.004
Kernel: built-in kernel
Third-Party Mods: none

### Acknowledgements

- [X] I have checked that the device is officially supported (for device specific reports and not source related).
- [X] I am running the latest version available on projectelixiros.com for this device.
- [X] I have searched the existing issues and this is a new issue and not a duplicate of any another open issue.
- [X] I have written a short but informative title.
- [X] I have filled out all of the requested information in this issue properly.

**Comment by manidweep** [comment]
no source requests

**Comment by TekkertheChaot** [comment]
So this behaviour is not a bug?
