### ISSUE TITLE
[Bug]: NearbyShare / QuickShare: not working - phone can't search for other devices and can itself not be discovered

### ISSUE THREAD

**Issue by TekkertheChaot** [Project-Elixir/issue_tracker#31]
### Issue type

Other

### Exact version and Build date

V4.1 | UQ1A.240205.004

### Bug Description

Quick Share (formerly know as Nearby Share) can not find other devices, although all visibilty settings have been adjusted accordingly (visible to all, accept from all). It also can not find other active devices, which all can find eachother.

### Steps to Reproduce

Step 1: go to Settings -> Connected Devices -> Connection preferences -> Nearby Share
Step 2: set a device name
Step 3: enable device visibility
Step 4: go to Device visibility
Step 5: set device visibility to "Everyone"
(optional, just to make sure) Step 6: Select "Keep everyone mode on all the time"

Step 7: 
try to send a file from another "nearby share"-enabled device to the device you just configured (testing visibilty)
\- or - 
try to send a file from the device you just configured to another "nearby share"-enabled device (testing search)

### Additional Context

Device: fajita (OnePlus 6T)
Rooted: false
Magisk modules: none
Build: UQ1A.240205.004
Kernel: built-in kernel
Third-Party Mods: none

### Acknowledgements

- [X] I have checked that the device is officially supported (for device specific reports and not source related).
- [X] I am running the latest version available on projectelixiros.com for this device.
- [X] I have searched the existing issues and this is a new issue and not a duplicate of any another open issue.
- [X] I have written a short but informative title.
- [X] I have filled out all of the requested information in this issue properly.

**Comment by manidweep** [comment]
no logs = no fixed for device side issues

**Comment by TekkertheChaot** [comment]
I am currently reproducing the issue and producing logs...

**Comment by manidweep** [comment]
where are the logs file, you are reproducing the bug and not giving any log file for us to check with

**Comment by TekkertheChaot** [comment]
Sorry for the wait, I was trying to record it usefully...

Logs and video of reproducing are available on my cloud (due to github filesize limits): https://cloud.jjmn.de/s/sx8zWxnd6qsPfWn
video has timestamps synced to the logcat.

_Currently only containing Video and Logcat of the usecase where I try to receive a file but my phone cannot be found.
I am working on recording also the case for sending._

**Comment by TekkertheChaot** [comment]
Okay, curiously after a few restarts, I can send files via Quick Share / Nearby Share. 
I still can NOT receive files as my device is not discoverable although my visibitlity settings are all set to everyone / public.
Please reopen. ;)
