### ISSUE TITLE
[Bug]: Pocket Mode: currently also triggers on flat surfaces

### ISSUE THREAD

**Issue by TekkertheChaot** [Project-Elixir/issue_tracker#33]
### Issue type

Feature not working as intended

### Exact version and Build date

V4.1 | UQ1A.240205.004

### Bug Description

Pocket Mode is (as far as I understand) a feature to prevent accidental activation and presses while tho phone is in a pocket. (duh)
Currently it seems to only take the devices gyroscope into consideration when to activate the protection (phone points downwards).
This does somewhat work, as long aus you put your phone upside down into the pocket. 
Unfortunately, when I slip my phone in my bag or into a larger puch, it slides freely and can end up in a position, where it is unprotected. 

### Steps to Reproduce

Step 1: enable pocket mode
Step 2: turn off the screen
Step 3: put your phone upside up into a pocket
Step 4: turn on the screen and take a peek into the pocket.
Result: Screen is not protected by pocket mode

### Solution

Adding a additional check for the proximity sensor as a condition (Maybe even add the option in the setting which conditions for the pocket mode apply, so the user can decide)

### Additional Context

Device: fajita (OnePlus 6T)
Rooted: false
Magisk modules: none
Build: UQ1A.240205.004
Kernel: built-in kernel
Third-Party Mods: none

### Acknowledgements

- [X] I have checked that the device is officially supported (for device specific reports and not source related).
- [X] I am running the latest version available on projectelixiros.com for this device.
- [X] I have searched the existing issues and this is a new issue and not a duplicate of any another open issue.
- [X] I have written a short but informative title.
- [X] I have filled out all of the requested information in this issue properly.

**Comment by manidweep** [comment]
device side issues, kindly provide logs

**Comment by manidweep** [comment]
also report to your maintainer

**Comment by TekkertheChaot** [comment]
How do I report to my maintainer? In patreon, telegram and here I get told to contact the maintainer, but when I ask how I would do that I either get no answer or get told to post it in the telegram support channel which in turn gets flooded and ignored.
I am at a loss where and how to report this stuff!

**Comment by manidweep** [comment]
report to your maintainer via messaging them personally in telegram

**Comment by TekkertheChaot** [comment]
Alright, will do. Thank you!
