### ISSUE TITLE
[Safety Suggestion]: Let user choose if contactless payment should be possible on locked screen

### ISSUE THREAD

**Issue by TekkertheChaot** [Project-Elixir/issue_tracker#34]
### Issue type

Source code related

### Exact version and Build date

V4.1 | UQ1A.240205.004

### Bug Description

Currently I am able to make contactless payments without unlocking my phone.
This makes the phone vulnerable to scammers scimming contactles card readers by simply walking by.
On ElixirOS 3,13 (if I remember correctly) payment was only able with unlocked phone or there was a setting to force this behaviour.

I am using all the same wallet and payment apps as before so it doesn't seem to be a problem from the payment apps themselves.

### Steps to Reproduce

(Payment)
Step 1: just hold the phone to a payment terminal without unlocking it.

### Solution

Add a option in the settings to let the user decide if contactless payments should be made without unlocking the screen.

### Additional Context

Device: fajita (OnePlus 6T)
Rooted: false
Magisk modules: none
Build: UQ1A.240205.004
Kernel: built-in kernel
Third-Party Mods: none

### Acknowledgements

- [X] I have checked that the device is officially supported (for device specific reports and not source related).
- [X] I am running the latest version available on projectelixiros.com for this device.
- [X] I have searched the existing issues and this is a new issue and not a duplicate of any another open issue.
- [X] I have written a short but informative title.
- [X] I have filled out all of the requested information in this issue properly.

**Comment by manidweep** [comment]
no source requests

**Comment by TekkertheChaot** [comment]
Okay, wait a minute, does source in this case mean AOSP Source or ElexirOS source? I thought it was ElixirOS

**Comment by manidweep** [comment]
we dont take source requests as in feature requests
