### ISSUE TITLE
[Bug]: message bug

### ISSUE THREAD

**Issue by tinthegamer05** [Project-Elixir/issue_tracker#4]
### Issue type

User interface

### Exact version and Build date

V3.12, 25-09-2023

### Bug Description

an app keeps crashing when it's not even open and when I have that message the app had stopped it closes directly and it keeps happening 

### Steps to Reproduce

An message bug

### Acknowledgements

- [X] I have checked that the device is officially supported (for device specific reports and not source related).
- [X] I am running the latest version available on projectelixiros.com for this device.
- [X] I have searched the existing issues and this is a new issue and not a duplicate of any another open issue.
- [X] I have written a short but informative title.
- [X] I have filled out all of the requested information in this issue properly.

**Comment by nishant6342** [comment]
Mention the name of app too that crashes
