### ISSUE TITLE
[Bug]: volume distortion above 60% volume /Realme 7 

### ISSUE THREAD

**Issue by Srvbadoni** [Project-Elixir/issue_tracker#40]
### Issue type

Source code related

### Exact version and Build date

V 4.1 / latest build 

### Bug Description

Volume is getting so irritating above 60% 

### Steps to Reproduce

Just raise volume above 60 %

### Acknowledgements

- [X] I have checked that the device is officially supported (for device specific reports and not source related).
- [X] I am running the latest version available on projectelixiros.com for this device.
- [X] I have searched the existing issues and this is a new issue and not a duplicate of any another open issue.
- [X] I have written a short but informative title.
- [X] I have filled out all of the requested information in this issue properly.

**Comment by ugly-kid-af** [comment]
Dont report device bug here and at least use from common sense !!
