### ISSUE TITLE
Dynamic island not working [Bug]: 

### ISSUE THREAD

**Issue by Srvbadoni** [Project-Elixir/issue_tracker#41]
### Issue type

Feature not working as intended

### Exact version and Build date

V4.1 latest build , build date 21 Feb 24

### Bug Description

Dynamic island not working 

### Steps to Reproduce

Just on that feature

### Acknowledgements

- [X] I have checked that the device is officially supported (for device specific reports and not source related).
- [X] I am running the latest version available on projectelixiros.com for this device.
- [X] I have searched the existing issues and this is a new issue and not a duplicate of any another open issue.
- [X] I have written a short but informative title.
- [X] I have filled out all of the requested information in this issue properly.

**Comment by ugly-kid-af** [comment]
Its working fine af
